name: Playwright Tests
on:
  repository_dispatch:
      types: [trigger-e2e-tests]
  push:
    branches: [ main, master, CI_testing ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      app:
        image: node:16  # Use a base image for your app's environment
        options: >-
          --health-cmd="curl --silent --fail localhost:3000 || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        ports:
          - 3000:3000  # Expose port 3000 on the container
        env:
          NODE_ENV: production
    steps:
      # Step 1: Checkout the e2e tests repository
      - name: Checkout e2e test repository
        uses: actions/checkout@v4
        with:
          repository: cryptpad/e2e-test-suite
          ref: CI_testing

      # Step 2: Set up Node.js for Playwright tests
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install Playwright dependencies
      - name: Install Playwright dependencies
        run: |
          npm ci
          npx playwright install --with-deps  # Install Playwright browsers

      # Step 4: Checkout the app repository
      - name: Checkout app repository
        uses: actions/checkout@v4
        with:
          repository: cryptpad/cryptpad
          # token: ${{ secrets.GITHUB_TOKEN }}

      # Step 5: Install app dependencies
    - run: npm install
    - run: npm run install:components
    - run: npm run dev &

      # # Step 6: Start the app in the background
      # - name: Start app in the background
      #   run: |
      #     npm start &  # Start the app in the background
      #     sleep 10  # Wait for the app to be fully available

      # Step 7: Run Playwright tests
      - run: npx playwright test anon --project='chrome'
        env: 
          PW_URL: ${{ vars.PW_URL }}





# jobs:
#   test:
#     timeout-minutes: 60
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v4
#     - uses: actions/setup-node@v4
#       with:
#         node-version: lts/*
#     - uses: actions/checkout@main
#     - name: Install dependencies
#       run: npm ci
#     - name: Install Playwright Browsers
#       run: npx playwright install --with-deps


#     - uses: actions/checkout@v4
#       with:
#           repository: cryptpad/cryptpad
#           ref: GHA_simultaneous_tests
#     - name: Use Node.js 18.15.0
#       uses: actions/setup-node@v3
#       with:
#         node-version: 18.15.0
#         cache: 'npm'
#     - run: npm install
#     - run: npm run install:components
#     # - run: npm run dev && npm run playwright-test-anon
#     - run: npm run playwright-test-anon
#       env: 
#         PW_URL: ${{ vars.PW_URL }}



# name: Playwright Tests
# on:
#   repository_dispatch:
#       types: [trigger-e2e-tests]
#   push:
#     branches: [ main, master, CI_testing ]
#   pull_request:
#     branches: [ main, master ]

# jobs:
#   setup:
#     timeout-minutes: 60
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v4
#       with:
#           repository: cryptpad/cryptpad
#           ref: GHA_simultaneous_tests
#     - name: Use Node.js 18.15.0
#       uses: actions/setup-node@v3
#       with:
#         node-version: 18.15.0
#         cache: 'npm'
#     - run: npm install
#     - run: npm run install:components
#     - run: npm run dev
#   test:
#     timeout-minutes: 60
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v4
#     - uses: actions/setup-node@v4
#       with:
#         node-version: lts/*
#     - uses: actions/checkout@main
#     - name: Install dependencies
#       run: npm ci
#     - name: Install Playwright Browsers
#       run: npx playwright install --with-deps
#     - name: check url
#       run: echo ${{ vars.PW_URL }} 
#       env: 
#         PW_URL: ${{ vars.PW_URL }} 
#     - name: Run tests
#       run: npx playwright test anon --project='chrome' --workers=2
#       env: 
#         PW_URL: ${{ vars.PW_URL }} 


    # - uses: actions/checkout@v4
    #   with:
    #       repository: cryptpad/cryptpad
    #       ref: GHA_simultaneous_tests
    # - name: Use Node.js 18.15.0
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: 18.15.0
    #     cache: 'npm'
    # - run: npm install
    # - run: npm run install:components
    # # - run: npm run dev && npm run playwright-test-anon
    # - run: npm run playwright-test-anon
    #   env: 
    #     PW_URL: ${{ secrets.PW_URL }}
    #//////

    # - name: Run Playwright tests
    #   run: npx playwright test anon --project='chrome' --workers=2
    #   env: 
    #     PW_URL: ${{ secrets.PW_URL }}
    # - uses: actions/upload-artifact@v4
    #   if: ${{ !cancelled() }}
    #   with:
    #     name: playwright-report
    #     path: playwright-report/
    #     retention-days: 30


    # - uses: actions/checkout@v4
    # - uses: actions/setup-node@v4
    #   with:
    #     node-version: lts/*
    # - uses: actions/checkout@main
    # - name: Set up SSH key
    #   uses: webfactory/ssh-agent@v0.9.0
    #   with:
    #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    # - name: Deploy via SSH-18
    #   run: |
    #     ${{ secrets.SSH }}
    # - name: Install dependencies
    #   run: npm ci
    # - name: Install Playwright Browsers
    #   run: npx playwright install --with-deps
    # - name: Run Playwright tests
    #   run: npx playwright test anon --project='chrome' --workers=2
    #   env: 
    #     PW_URL: ${{ secrets.PW_URL }}
    # - uses: actions/upload-artifact@v4
    #   if: ${{ !cancelled() }}
    #   with:
    #     name: playwright-report
    #     path: playwright-report/
    #     retention-days: 30