name: Playwright tests - local instance
on:
  repository_dispatch:
      types: [trigger-e2e-tests]
  push:
    branches: [ CI_testing ]

jobs:
  start_app:
    runs-on: ubuntu-latest 
    services:
      app:
        image: node:22  
        ports:
          - 3000:3000 
    steps:
      - name: Run multi repo cloning script
        env: 
            PA_TOKEN: ${{ secrets.PAT_SECRET }} 
        run: git clone "https://"$PA_TOKEN"@github.com/cryptpad/cryptpad.git" -b CI_testing
        shell: bash
      - name: Install dependencies
        run: npm install --prefix cryptpad
      - name: Install components  
        run: npm run install:components --prefix cryptpad
      - name: Install OnlyOffice
        run: cryptpad/install-onlyoffice.sh -a 
      - name: Run local server
        timeout-minutes: 180
        run: nohup npm run dev --prefix cryptpad &
      - name: Run multi repo cloning script
        env: 
            PA_TOKEN: ${{ secrets.PAT_SECRET }} # 
        run: git clone "https://"$PA_TOKEN"@github.com/cryptpad/e2e-test-suite.git"
        shell: bash
      - name: Install dependencies
        run: npm ci --prefix e2e-test-suite
      - name: Install dependencies
        run: npm exec playwright install --with-deps --prefix e2e-test-suite
      - name: Install dependencies
        run: npm exec playwright test form_anon.spec.js --project='chrome' --workers=2 --prefix e2e-test-suite
        env:
          PW_URL: ${{ vars.PW_URL }} 
