name: Playwright Tests
on:
  repository_dispatch:
      types: [trigger-e2e-tests]
  push:
    branches: [ main, master, CI_testing ]
  pull_request:
    branches: [ main, master ]

jobs:
  start_app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout app repository
        uses: actions/checkout@v4
        with:
          repository: cryptpad/cryptpad
          ref: GHA_simultaneous_tests
      - name: Use Node.js 18.15.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.0
          cache: 'npm'
      - run: npm install
      - run: npm run install:components
      - run: npm run dev 
      # - name: Install app dependencies
      #   run: |
      #     npm install

      # - name: Start app
      #   run: |
      #     npm start &  # Start the app in the background
        # env:
        #   NODE_ENV: production
        continue-on-error: true  # Allow the step to complete even if the app process is terminated

      - name: Wait for app to start
        run: |
          # You can add a small sleep or check that localhost:3000 is available
          sleep 10  # Wait for the app to be up and running on localhost:3000

  run_tests:
    needs: start_app  # This ensures the test job runs after the app is started
    runs-on: ubuntu-latest
    steps:
      - name: Checkout test repository
        uses: actions/checkout@v4
        with:
          repository: cryptpad/e2e-test-suite
          ref: CI_testing

      - name: Install components
        run: |
          npm ci

      - name: Install deps
        run: |
          npm ci
          
      - name: Run Playwright tests
        run: |
          npx playwright install --with-deps  # Install Playwright dependencies
          npx playwright test anon --project='chrome'  # or whatever command runs your tests
        env:
          BASE_URL: http://localhost:3000  # Set the app's URL for Playwright to use











# jobs:
#   test:
#     timeout-minutes: 60
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v4
#     - uses: actions/setup-node@v4
#       with:
#         node-version: lts/*
#     - uses: actions/checkout@main
#     - name: Install dependencies
#       run: npm ci
#     - name: Install Playwright Browsers
#       run: npx playwright install --with-deps


#     - uses: actions/checkout@v4
#       with:
#           repository: cryptpad/cryptpad
#           ref: GHA_simultaneous_tests
#     - name: Use Node.js 18.15.0
#       uses: actions/setup-node@v3
#       with:
#         node-version: 18.15.0
#         cache: 'npm'
#     - run: npm install
#     - run: npm run install:components
#     # - run: npm run dev && npm run playwright-test-anon
#     - run: npm run playwright-test-anon
#       env: 
#         PW_URL: ${{ vars.PW_URL }}



# name: Playwright Tests
# on:
#   repository_dispatch:
#       types: [trigger-e2e-tests]
#   push:
#     branches: [ main, master, CI_testing ]
#   pull_request:
#     branches: [ main, master ]

# jobs:
#   setup:
#     timeout-minutes: 60
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v4
#       with:
#           repository: cryptpad/cryptpad
#           ref: GHA_simultaneous_tests
#     - name: Use Node.js 18.15.0
#       uses: actions/setup-node@v3
#       with:
#         node-version: 18.15.0
#         cache: 'npm'
#     - run: npm install
#     - run: npm run install:components
#     - run: npm run dev
#   test:
#     timeout-minutes: 60
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v4
#     - uses: actions/setup-node@v4
#       with:
#         node-version: lts/*
#     - uses: actions/checkout@main
#     - name: Install dependencies
#       run: npm ci
#     - name: Install Playwright Browsers
#       run: npx playwright install --with-deps
#     - name: check url
#       run: echo ${{ vars.PW_URL }} 
#       env: 
#         PW_URL: ${{ vars.PW_URL }} 
#     - name: Run tests
#       run: npx playwright test anon --project='chrome' --workers=2
#       env: 
#         PW_URL: ${{ vars.PW_URL }} 


    # - uses: actions/checkout@v4
    #   with:
    #       repository: cryptpad/cryptpad
    #       ref: GHA_simultaneous_tests
    # - name: Use Node.js 18.15.0
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: 18.15.0
    #     cache: 'npm'
    # - run: npm install
    # - run: npm run install:components
    # # - run: npm run dev && npm run playwright-test-anon
    # - run: npm run playwright-test-anon
    #   env: 
    #     PW_URL: ${{ secrets.PW_URL }}
    #//////

    # - name: Run Playwright tests
    #   run: npx playwright test anon --project='chrome' --workers=2
    #   env: 
    #     PW_URL: ${{ secrets.PW_URL }}
    # - uses: actions/upload-artifact@v4
    #   if: ${{ !cancelled() }}
    #   with:
    #     name: playwright-report
    #     path: playwright-report/
    #     retention-days: 30


    # - uses: actions/checkout@v4
    # - uses: actions/setup-node@v4
    #   with:
    #     node-version: lts/*
    # - uses: actions/checkout@main
    # - name: Set up SSH key
    #   uses: webfactory/ssh-agent@v0.9.0
    #   with:
    #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    # - name: Deploy via SSH-18
    #   run: |
    #     ${{ secrets.SSH }}
    # - name: Install dependencies
    #   run: npm ci
    # - name: Install Playwright Browsers
    #   run: npx playwright install --with-deps
    # - name: Run Playwright tests
    #   run: npx playwright test anon --project='chrome' --workers=2
    #   env: 
    #     PW_URL: ${{ secrets.PW_URL }}
    # - uses: actions/upload-artifact@v4
    #   if: ${{ !cancelled() }}
    #   with:
    #     name: playwright-report
    #     path: playwright-report/
    #     retention-days: 30