name: Playwright tests - local instance
on:
  repository_dispatch:
      types: [trigger-e2e-tests]
  push:
    branches: [ testing_branch ]

jobs:
  start_app:
    runs-on: ubuntu-latest 
    services:
      app:
        image: node:22  
        ports:
          - 3000:3000 
    steps:
      - name: Clone CryptPad repository
        env: 
            PA_TOKEN: ${{ secrets.PAT_SECRET }} 
        run: git clone "https://"$PA_TOKEN"@github.com/cryptpad/cryptpad.git" 
        shell: bash
      - name: Install dependencies
        run: npm install --prefix cryptpad
      - name: Install components  
        run: npm run install:components --prefix cryptpad
      - name: Install OnlyOffice
        run: cryptpad/install-onlyoffice.sh -a 
      - name: Run local server
        timeout-minutes: 180
        run: nohup npm run dev --prefix cryptpad &
      - name: Clone test repository
        env: 
            PA_TOKEN: ${{ secrets.PAT_SECRET }} # 
        run: git clone "https://"$PA_TOKEN"@github.com/cryptpad/e2e-test-suite.git" -b testing_branch
        shell: bash
      - name: Install dependencies
        run: npm ci --prefix e2e-test-suite
      - name: Install dependencies 2
        run: npm exec playwright install --with-deps --prefix e2e-test-suite
      - name: Install test reporter
        run: npm install playwright-ctrf-json-reporter --prefix e2e-test-suite
      - name: Run tests
        run: npm exec playwright test homepage_anon.spec.js:37 --project='chrome' --workers=2 --prefix e2e-test-suite
        env:
          PW_URL: ${{ vars.PW_URL }} 
      - name: Publish Test Report
        uses: ctrf-io/github-test-reporter@v1
        with:
          report-path: './ctrf/*.json'
        if: always()